"""add constraints

Revision ID: 882893c3a7a1
Revises:
Create Date: 2026-08-24 21:50:16.555945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "882893c3a7a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f("ck_users_age"), "users", "age >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_age"), "users", type_="check")
    # ### end Alembic commands ###
